### ISSUE TITLE
Windows (dev build fail)

### ISSUE THREAD

**Issue by kustomzone** [happybeing/p2p-git-portal-wasi#2]
Creating issue rather than PR for general reference.

**Platform: amd64, Win 10, mingw64.**

### Context

Working setup with all prerequisites; Rust, Node.js, Visual Studio Build Tools 2019 (+Win SDK 10).

### Process

**[fails]** `yarn && yarn dev-wasm-bindgen && yarn dev`

Compiles "src/wasi-rust/target/wasm32-wasi/debug".
Throws error;

> The syntax of the command is incorrect. error Command failed with exit code 1.

**[works]** `yarn`
**[fails]** `yarn dev-wasm` 

Compiles, above error thrown, "public/wasm" folder **NOT** created, **halts in root (main) folder**.
Try the commands directly...

**[works - in the console]** `cd src/wasi-rust/ && cargo build --target=wasm32-wasi && mkdir -p ../../public/wasm`

Compiles, "public/wasm" folder **IS** created, **halts in "src/wasi-rust" folder** (!!!)
But next command **MUST** be run from root! > `cd ../..`

**[works]** `wasm-bindgen --no-typescript src/wasi-rust/target/wasm32-wasi/debug/wasi-gitportal.wasm --debug --keep-debug  --out-dir .`

Next command...

**[fails]** `yarn wbg-to-wasi`

Popup error; "M$ JScript compilation error"  .. yes **JScript!**  :)
**Solution**: ...run it with `node`.

**[works]** `node ./scripts/wbg_to_wasi.js --path ./wasi-js/ wasi-gitportal_bg.js wasi-gitportal_bg_wasi.js`

Lastly, create "public/wasm" folder if failed above. > `mkdir -p public/wasm`

**[works]** `mv *.wasm public/wasm/ && mv wasi-* src`

Start server...

**[works]** `yarn dev`

Success!

## Found Solution

When using `yarn` my `mkdir -p folder/subfolder` is not working as it should.
eg. If **"new-dir": "mkdir --help"** in  package.json, then `yarn new-dir` creates an empty "--help" directory.
In the console `mkdir --help` and all other parameters work correctly.

Temporary solution which works;  `cd public && mkdir wasm && cd ..` 

`where mkdir` returns "C:\Program Files\Git\usr\bin\mkdir.exe" ..and all works normally when NOT using YARN.

The following package.json code works for me, but i haven't tested on Linux or Mac. (so same code for both)

[package.txt](https://github.com/happybeing/p2p-git-portal-wasi/files/5933612/package.txt)

Windows: ` yarn && yarn build-dev-windows && yarn dev`
Likewise for Linux and Mac.

Haven't run the tests. Please check the code.
Only mkdir was failing. **mv** and **rm** were working normally from YARN.
Cheers!

**Comment by happybeing** [comment]
This is excellent thanks. I found two issues:
- `cleanup` was failing when `wasm` exists until I inserted `rm -rf wasm && ` before the `mkdir`:
   ` "cleanup": "cd public && rm -rf wasm && mkdir wasm && cd .. && rm -f public/wasm/* && mv *.wasm public/wasm/ && mv wasi-* src/ && yarn docs",`
- your build commands only generate the wasm and bindings, but don't generate the app bundles because the `build-app` command is missing. So for example this works:
   `"build-app": "cross-env NODE_ENV=production webpack",`
   `  "build-release-linux": "yarn build-release && yarn wbg-to-wasi && yarn build-app",`

I find that `yarn build-release-windows` also works for me on Ubuntu so I suggest using the following and eliminating the different OS versions:
   `"build-release": "yarn build-release && yarn wbg-to-wasi-node && yarn build-app",`

Then also remove the `wbg-to-wasi`. If you want to open a PR the CI should show if they're still ok on Linux, or I can check out an updated package.txt if you prefer.


[package.txt](https://github.com/happybeing/p2p-git-portal-wasi/files/5934043/package.txt)

**Comment by happybeing** [comment]
Also, I missed you're building for `yarn dev` but don't need to do `build-webpack` as the `webpack-dev-server` builds the bundles in memory (and rebuilds on changes). So this original `dev` command is enough:
"dev": "webpack-dev-server --watch-content-base --content-base public",

You do need to add `yarn build-webpack` to the end of the `build-release` command, or the bundles aren't rebuilt. Test by checking dates of `./public/bundle.*`, and then remove them and try `yarn test:build`.

**Comment by kustomzone** [comment]
Works for me.
Will check the dates as you suggest.

Updated. Removed `build-app` from `build-dev`.  [package.txt](https://github.com/happybeing/p2p-git-portal-wasi/files/5935279/package.txt)


Closing, but if someone knows why MKDIR is not working under YARN then let me know what's happened. 
Thanks for your help Happybeing!

**Comment by happybeing** [comment]
`yarn` will look for a command in `package.json` called `mkdir`. So you would omit `yarn`, and just have `&& mkdir`

**Comment by kustomzone** [comment]
didn't have `yarn mkdir` ...just like the example; "new-dir": "mkdir --help" ... `yarn new-dir`  = made a "--help" folder.
(same for -v  -p  --version)  Also failed with 'folder/subfolder'. (hence the fix above)  Very weird!

**Comment by happybeing** [comment]
Must be a Windows issue, but I'm not sure what the culprit is. If `npm run new-dir` does the same then it's not `yarn` but I'm not sure where it points to.

**Comment by kustomzone** [comment]
Normally it's something like the space in "Program Files/Git..." but YARN is handling RM / MV which are in the same folder as MKDIR.exe. (where bash.exe is) And spaces in MingW show up as "Program\ Files" ...just to make things even more confusing.
In short, `mkdir foldername` works, but not the parameters or paths.

**Comment by kustomzone** [comment]
Asset       Size             Chunks                 Chunk Names
bundle.css  508 bytes       0  [emitted]           bundle
 bundle.js    272 KiB          0  [emitted]  [big]  bundle
Entrypoint bundle [big] = bundle.css bundle.js
...
TESTING ON BUILD
index.js
buildserver on port 5111
githttpserver on port 5222
puppeteer setup()
• • • puppeteer reset()
buildserver shut down
githttpserver shut down
  (3 / 3)
  Total:     3
  Passed:    3
  Skipped:   0
  Duration:  2716.26ms
